### PR TITLE
feat: add init and snapshot functionality

### PR DESCRIPTION
**Pull request by edfloreshz**
This PR implements `init` and `snapshot` functionality.

`restore`  should also work but it is not yet tested, keeping this as a draft until we test.

### CODE REVIEW

**Comment by ahoneybun** [comment]
I'm not sure why it is failing the build yet it builds locally with the same command... I also have issue using `restic` itself to open the repository. 

Screenshot from 2024-05-20 11-37-31

**Comment by ahoneybun** [comment]
Alright so it works on Nobara (Fedora) with version 0.16.2 vs Pop (Ubuntu) with version 0.12.1.

**Comment by edfloreshz** [comment]
My tests have been successful so far, we can merge if you're okay with it.

**Review by ahoneybun — APPROVED** [review]
Looks good in testing with `cargo test`.

**Pull request merged**
